### ISSUE TITLE
Add CoffeeScript as a dependency.

### ISSUE THREAD

**Issue by derhuerst** [1p6/ascii-art#1]
The [`package.json` `dependencies` field](https://docs.npmjs.com/files/package.json#dependencies) has been created for this.

I'm willing to create a pull request for this.

**Comment by 1p6** [comment]
[Added coffeescript as a devDependency](https://github.com/1p6/fonts.js/commit/ff067b61c2d8ca649b23def375f73a3c05a58580) because it is not needed to use this library.
Also, good luck creating a font.
